
export const WORK_POST_REQUEST = 'WORK_POST_REQUEST';
export const WORK_POST_RECEIVED = 'WORK_POST_RECEIVED';
export const WORK_POST_ERROR = 'WORK_POST_ERROR';
export const WORK_POST_ADD = 'WORK_POST_ADD';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_RECEIVED = 'POST_RECEIVED';
export const POST_ERROR = 'POST_ERROR';
export const POST_UNLOAD = 'POST_UNLOAD';

export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST';
export const QUESTION_LIST_RECEIVED = 'QUESTION_LIST_RECEIVED';
export const QUESTION_LIST_ERROR = 'QUESTION_LIST_ERROR';
export const QUESTION_LIST_UNLOAD = 'QUESTION_LIST_UNLOAD';

export const QUESTION_ADDED = 'QUESTION_ADDED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';